# Generated by Django 5.2.7 on 2025-10-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
