# Generated by Django 5.2.7 on 2025-10-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
